services:

  asy-backend:
    build:
      context: ./asy-backend
      dockerfile: ./Dockerfile
      args:
        USER_UID: 1000
    container_name: asy-webapp
    restart: always
    environment:
      - LIBGS=/usr/lib/x86_64-linux-gnu/libgs.so.10
      - ASYMPTOTE_PORT=80
    volumes:
      - ./asy-backend/asy_extra_modules:/home/asymptote/.asy:ro
    ports:
      - "0.0.0.0:9527:80"
